### ISSUE TITLE
You are sending RSS feed data to your web server, please add it to Project readme.md

### ISSUE THREAD

**Issue by korifeich** [NarroApp/Pb#1]
You are sending rss feed to be parsed to your server, so anyone who is using you lib need to be aware of it, because of several reasons:
- In case you server stop working, all widgets that are using your lib will stop working
- It is not secured to send RSS data to some third party web servers.

**Comment by joshbeckman** [comment]
Right you are! Originally, the library attempted to parse the RSS/podcast/XML data client-side, but ran into issues with bundle size and CORS errors, so the server is now used to parse the RSS feed itself. The README was left behind!

I'll update the README shortly.
